version: '3'
services:
  api:
    image: screenshot-api:latest
    environment:
      MAX_CACHE_SECONDS: 30
    ports:
      - 35001:3000
  # Use nginx to throttle requests
  nginx:
    image: nexus.ecri.org/dev/nginx:1.0.0
    volumes:
      - ./ci/docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - 35002:8080
  # Use varnish for caching
  varnish:
    image: varnish:6.3
    volumes:
      - ./ci/docker-compose/varnish/default.vcl:/etc/varnish/default.vcl:ro
    depends_on:
      - nginx
    ports:
      - 35003:80
